# Generated by Django 5.2.1 on 2026-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=22)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=343, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
