# Generated by Django 5.2.1 on 2026-03-05 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
